course_work/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls', namespace="home_page")),
]

home_page/urls.py
from django.urls import path
from . import views

app_name = 'home_page'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('model/', views.model, name='model'),
    path('model/classify/', views.classify_image, name='classify_image'),
    path('model/model_view/', views.model_view, name='model_view'),
]

home_page/models.py
from django.db import models


# Create your models here.

class DataEntry(models.Model):
    boolean_value = models.BooleanField()

    def __str__(self):
        return str(self.boolean_value)

home_page/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from keras.models import load_model
import os
import cv2
import numpy as np
from .models import DataEntry


# Create your views here.
def home_page(request):
    return render(request, 'home_page/home_page.html')


def model(request):
    return render(request, 'home_page/model.html')


def classify_image(request):
    if request.method == 'POST' and request.FILES['photo']:
        image = request.FILES['photo']
        model = load_model(os.path.join('models', 'classifier.h5'))
        img = cv2.imdecode(np.frombuffer(image.read(), np.uint8), cv2.IMREAD_COLOR)
        resize = cv2.resize(img, (256, 256))
        yhat = model.predict(np.expand_dims(resize / 255, 0))
        predicted_class = '''Model can't recognize that image''' if yhat[0][0] >= 0.99 or yhat[0][0] < 0.1 else 'Normal' if yhat[0][0] > 0.7 else 'Defected'
        print(yhat[0][0])
        return JsonResponse({'predicted_class': predicted_class})
    else:
        return JsonResponse({'error': 'Image file is missing or invalid.'})


from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def model_view(request):
    if request.method == 'POST':
        boolean_value = int(request.POST.get('boolean_value', 0))
        DataEntry.objects.create(boolean_value=boolean_value)

    data_entries = DataEntry.objects.all()
    total_entries = len(data_entries)
    true_entries = data_entries.filter(boolean_value=1).count()
    accuracy = (true_entries / total_entries) * 100 if total_entries > 0 else 0
    rounded_accuracy = round(accuracy, 2)

    return HttpResponse(str(rounded_accuracy))

home_page/templates/home_page/home_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href={% static 'assets/bootstrap/css/bootstrap.min.css' %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-md sticky-top py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-bezier">
                        <path fill-rule="evenodd" d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                        <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                    </svg></span><span>Recognize model</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'home_page:home_page' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'home_page:model' %}">Model</a></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="bg-dark">
        <div class="container pt-4 pt-xl-5">
            <div class="row pt-5">
                <div class="col-md-8 col-xl-6 text-center text-md-start mx-auto">
                    <div class="text-center">
                        <p class="fw-bold text-success mb-2"></p>
                        <h1 class="fw-bold">Recognize model</h1>
                    </div>
                </div>
                <div class="col-12 col-lg-10 mx-auto">
                    <div class="position-relative" style="display: flex;flex-wrap: wrap;justify-content: flex-end;">
                        <div style="position: relative;flex: 0 0 45%;transform: translate3d(-15%, 35%, 0);"><img class="img-fluid" data-bss-parallax="" data-bss-parallax-speed="0.8" src={% static 'assets/img/products/ok000.png' %}></div>
                        <div style="position: relative;flex: 0 0 45%;transform: translate3d(-5%, 20%, 0);"><img class="img-fluid" data-bss-parallax="" data-bss-parallax-speed="0.4" src={% static 'assets/img/products/ok001.png' %}></div>
                        <div style="position: relative;flex: 0 0 60%;transform: translate3d(0, 0%, 0);"><img class="img-fluid" data-bss-parallax="" data-bss-parallax-speed="0.25" src={% static 'assets/img/products/scratch_neck008.png' %}></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="py-5"></section>
    <section>
        <div class="container bg-dark py-5">
            <div class="row">
                <div class="col-md-8 col-xl-7 text-center mx-auto">
                    <p class="fw-bold text-success mb-2">Our Services</p>
                    <h3 class="fw-bold">What should you know about recognize model</h3>
                </div>
            </div>
            <div class="py-5 p-lg-5">
                <p>Defect detection model is an advanced machine learning system designed to analyze uploaded photographs and determine whether a component exhibits any defects. By leveraging state-of-the-art computer vision algorithms, the model can accurately identify and classify various types of defects, such as cracks, scratches, deformations, or anomalies.<br><br>The model has been trained on a large dataset of labeled images, encompassing both defective and non-defective components. Through a combination of deep learning techniques and feature extraction, it has learned to recognize patterns and subtle indicators of defects, achieving high accuracy in its predictions.<br><br>To use the model, simply upload a photo of the component in question, and our system will process the image, extracting relevant features and analyzing them against the learned defect patterns. Within seconds, you will receive a result indicating whether the component is classified as defective or not.<br><br>Our defect detection model provides a reliable and efficient solution for quality control and inspection processes across various industries. By automating the defect detection process, it helps streamline operations, reduce human error, and ensure the delivery of high-quality components to customers.</p>
            </div>
        </div>
    </section>
    <section></section>
    <section class="py-5 mt-5"></section>
    <script src={% static 'assets/bootstrap/js/bootstrap.min.js' %}></script>
    <script src={% static 'assets/js/bold-and-dark.js' %}></script>
</body>

</html>

home_page/templates/home_page/model.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Services - Brand</title>
    <link rel="stylesheet" href={% static 'assets/bootstrap/css/bootstrap.min.css' %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-md sticky-top py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-bezier">
                        <path fill-rule="evenodd" d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                        <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                    </svg></span><span>Recognize model</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home_page:home_page' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'home_page:model' %}">Model</a></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="py-5">
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <p class="fw-bold text-success mb-2">Our Services</p>
                    <h3 class="fw-bold">Recognize model</h3>
                </div>
            </div>
            <div class="row row-cols-1 row-cols-md-2 mx-auto" style="max-width: 900px;">
                <div class="col mb-5"><img id="selected-image" src="#" alt=""></div>
                <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                    <div>
                        <h5 class="fw-bold">Class of detail is:</h5>
                        <p id="detail-class" class="text-muted mb-4"></p>
                    </div>
                </div>
                <div class="col">
                    <button class="btn btn-primary" type="button" onclick="document.getElementById('file-input').click()">Load photo</button>
                    <form method="post" enctype="multipart/form-data" style="display: none;">
                        {% csrf_token %}
                        <input id="file-input" type="file" name="photo" onchange="document.getElementById('upload-form').submit()">
                        <button id="submit-btn" type="submit">Upload photo</button>
                    </form>
                </div>
                <div class="col">
                    <div class="btn-group" role="group">
                        <div class="percentage-text">{{ accuracy }}%</div>
                        <button id="yes-btn" class="btn btn-primary" type="button">Yes</button>
                        <button id="no-btn" class="btn btn-primary" type="button">No</button>
                        <div class="percentage-text"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src={% static 'assets/bootstrap/js/bootstrap.min.js' %}></script>
    <script src={% static 'assets/js/bold-and-dark.js' %}></script>
    <script>
        function handleFileSelect(event) {
            var file = event.target.files[0];
            var reader = new FileReader();

            var img = document.getElementById('selected-image');
            reader.onload = function(e) {
                img.src = e.target.result;
            }

            reader.readAsDataURL(file);
            var formData = new FormData();
            formData.append('photo', file);

            var xhr = new XMLHttpRequest();
            xhr.open('POST', '/model/classify/', true);
            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            xhr.onload = function() {
                if (xhr.status === 200) {
                    var result = JSON.parse(xhr.responseText);
                    document.getElementById('detail-class').textContent = result['predicted_class'];
                }
                else {
                    alert('Error occurred while classifying the image. Please try again.');
                }
            };
            xhr.send(formData);
        }
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;}
                }
            }
            return cookieValue;
        }

        var fileInput = document.getElementById('file-input');
        fileInput.addEventListener('change', handleFileSelect, false);
    </script>

    <script>
        // Ожидаем загрузки страницы
        document.addEventListener('DOMContentLoaded', function() {
            // Получаем кнопки "Yes" и "No" по идентификаторам
            var yesBtn = document.getElementById('yes-btn');
            var noBtn = document.getElementById('no-btn');

            // Добавляем обработчики событий для кнопок
            yesBtn.addEventListener('click', function() {
                sendData(1); // Отправляем значение 1 (True) на сервер
            });

            noBtn.addEventListener('click', function() {
                sendData(0); // Отправляем значение 0 (False) на сервер
            });

            // Функция для отправки данных на сервер
            function sendData(booleanValue) {
                // Создаем новый объект XMLHttpRequest
                var xhr = new XMLHttpRequest();

                // Определяем метод и URL для отправки данных
                xhr.open('POST', '/model/model_view/', true);

                // Устанавливаем заголовки запроса
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');

                // Определяем обработчик события при завершении запроса
                xhr.onload = function() {
                    if (xhr.status === 200) {
                        // Обновляем процент точности на странице
                        var accuracyText = document.querySelector('.percentage-text');
                        accuracyText.textContent = xhr.responseText + '%';
                    }
                };

                // Формируем данные для отправки
                var data = 'boolean_value=' + booleanValue;

                // Отправляем запрос
                xhr.send(data);
            }
        });
    </script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var accuracyText = document.querySelector('.percentage-text');

            // Функция для отправки AJAX-запроса и обновления значения точности
            function fetchAccuracy() {
                var xhr = new XMLHttpRequest();
                xhr.open('GET', '/model/model_view/', true);

                xhr.onload = function() {
                    if (xhr.status === 200) {
                        accuracyText.textContent = xhr.responseText + '%';
                    }
                };

                xhr.send();
            }

            // Вызываем функцию при загрузке страницы
            fetchAccuracy();
        });
    </script>
</body>

</html>